// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: gobits.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createGobit = `-- name: CreateGobit :one
INSERT INTO gobits (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateGobitParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateGobit(ctx context.Context, arg CreateGobitParams) (Gobit, error) {
	row := q.db.QueryRowContext(ctx, createGobit, arg.Body, arg.UserID)
	var i Gobit
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteGobit = `-- name: DeleteGobit :exec
DELETE FROM gobits
WHERE id = $1 AND user_id = $2
`

type DeleteGobitParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteGobit(ctx context.Context, arg DeleteGobitParams) error {
	_, err := q.db.ExecContext(ctx, deleteGobit, arg.ID, arg.UserID)
	return err
}

const getAllGobits = `-- name: GetAllGobits :many
SELECT id, created_at, updated_at, body, user_id FROM gobits
ORDER BY created_at ASC
`

func (q *Queries) GetAllGobits(ctx context.Context) ([]Gobit, error) {
	rows, err := q.db.QueryContext(ctx, getAllGobits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gobit
	for rows.Next() {
		var i Gobit
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGobit = `-- name: GetGobit :one
SELECT id, created_at, updated_at, body, user_id FROM gobits WHERE id = $1
`

func (q *Queries) GetGobit(ctx context.Context, id uuid.UUID) (Gobit, error) {
	row := q.db.QueryRowContext(ctx, getGobit, id)
	var i Gobit
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
