// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: gobits.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createGobit = `-- name: CreateGobit :one
INSERT INTO gobits (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateGobitParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateGobit(ctx context.Context, arg CreateGobitParams) (Gobit, error) {
	row := q.db.QueryRowContext(ctx, createGobit, arg.Body, arg.UserID)
	var i Gobit
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
